module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    ID_OR_PW_NULL_VALUE: "아이디/비밀번호 값이 없습니다.",
    CREATED_USER: "회원 가입 성공",
    DELETE_USER: "회원 탈퇴 성공",
    
    ALREADY_ID : "이미 아이디가 존재합니다.",
    ALREADY_USER: "이미 회원입니다.",
    NO_USER: "존재하지 않는 회원입니다.",
    MISS_MATCH_PW: "비밀번호가 맞지 않습니다.",
    LOGIN_SUCCESS: "로그인 성공",
    LOGIN_FAIL: "로그인 실패",

    SAVE_SUCCESS: "데이터 저장 성공",
    SAVE_FAIL: "데이터 저장 실패",
    READ_FAIL: "데이터 읽기 실패",
    READ_SUCCESS : "데이터 읽기 성공",
    BOARD_EMPTY : "글이 없습니다.",
    BOARD_SUCCESS : "글 쓰기 성공",
    BOARD_FAIL : "글쓰기 실패",
    BOARD_DROP_FAIL : "글 삭제 실패",
    BOARD_DROP_SUCCESS:"글 삭제 성공",
    BOARD_IDX_NULL:"글을 찾을 수가 없음",
    EMPTY_LIST :"빠진 부분이 있습니다. 확인해 주세요",
    LIST_FAILE :"리스트 저장 실패",
    LIST_SUCCESS : "리스트 저장 성공",
    LIST_DELETE_FAILE : "리스트 삭제 실패",
    LIST_DELETE_SUCCESS : "리스트 삭제 성공",
    ALL_LIST_SUCCESS : "모든 리스트 가져오기 성공",
    ALL_LSIT_FAIL : "모든 리스트 가져오기 실패",
    EXPIRE_LIST_SUCCESS : "마감 기한 지난 리스트 가져오기 성공",
    EXPIRE_LIST_FAIL : "마감 기한 지난 리스트 가져오기 실패",
    EXPIRE_LIST_EMPTY : "마감 기한 지난 리스트 없음",
    A_LIST_SUCCESS : "리스트 가져오기 성공",
    A_LIST_FAIL : "리스트 가져오기 실패",
    COMPELTE_UPDATE_FAIL : "완료 업데이트 실패",
    COMPELTE_UPDATE_SUCCESS : "완료 업데이트 성공",
    

    STUDENT_SELECT_SUCCESS: "학생 조회 성공",
    NO_STUDENT: "존재하지 않는 학생입니다",
    STUDENT_SELECT_FAIL: "학생 조회 실패",

    POST_SLECET_FAILE:"같은 제목이 존재 합니다.",
};